remote_theme: chesterhow/tale
permalink: /:title
paginate: 5
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jemoji
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_enda
author:
  name: Joshua Eckroth
  url: https://www2.stetson.edu/~jeckroth/
  email: jeckroth@stetson.edu

